SET SEARCH_PATH = "schema_after_dop";
TRUNCATE TABLE "COMPUTERS", "LIGHTNING_STRIKES", "MEMORIES", "MONITORS", "PEOPLE", "RAMS", "WEB", "COMPONENTS_HEALTH";

ALTER SEQUENCE "COMPUTERS_id_seq" RESTART;
ALTER SEQUENCE "LIGHTNING_STRIKES_id_seq" RESTART;
ALTER SEQUENCE "MEMORIES_id_seq" RESTART;
ALTER SEQUENCE "MONITORS_id_seq" RESTART;
ALTER SEQUENCE "PEOPLE_id_seq" RESTART;
ALTER SEQUENCE "RAMS_id_seq" RESTART;
ALTER SEQUENCE "WEB_id_seq" RESTART;
